const channels = {
	preferences: {
		load: "preferences:load",
		save: "preferences:save",
		reset: "preferences:reset",
	},
	registry: {
		loadAll: "registry:load-all",
		getPath: "registry:get-path",
		getEntry: "registry:get-entry",
		has: "registry:has",
		getStatus: "registry:get-status",
		getAll: "registry:get-all",
		count: "registry:count",
	},
	extension: {
		load: "extension:load",
		homepage: "extension:homepage",
		mangaDetails: "extension:manga-details",
		mangaChapters: "extension:manga-chapters",
		chapterDetails: "extension:chapter-details",
		viewMore: "extension:view-more",
		searchResults: "extension:search-results",
		multiSearchResults: "extension:multi-search-results",
		searchTags: "extension:search-tags",
		info: "extension:info",
		metadata: "extension:metadata",
		capabilities: "extension:capabilities",
	},
	library: {
		get: "library:get",
		clearLibrary: "library:clear-library",
		addEntry: "library:add-entry",
		removeEntry: "library:remove-entry",
		getEntries: "library:get-entries",
		getEntriesByCategory: "library:get-entries-by-category",
		hasEntry: "library:has-entry",
		updateEntryMetadata: "library:update-entry-metadata",
		refreshAll: "library:refresh-all",
		refreshCategory: "library:refresh-category",
		isRefreshing: "library:is-refreshing",
		setRefreshProgressCallback: "library:set-refresh-progress-callback",
		getWithUnreadCounts: "library:get-with-unread-counts",
		getUnreadCount: "library:get-unread-count",
	},
	category: {
		addCategory: "category:add-category",
		rename: "category:rename",
		removeCategory: "category:remove-category",
		addCategoryToEntry: "category:add-category-to-entry",
		removeCategoryFromEntry: "category:remove-category-from-entry",
		reorder: "category:reorder",
	},
	history: {
		markAsRead: "history:mark-as-read",
		unmarkAsRead: "history:unmark-as-read",
		bulkMarkAsRead: "history:bulk-mark-as-read",
		bulkUnmarkAsRead: "history:bulk-unmark-as-read",
		clearManga: "history:clear-manga",
		clearSource: "history:clear-source",
		clearAll: "history:clear-all",
		getMangaReadLogs: "history:get-manga-read-entry",
		getHistoryEntries: "history:get-history-entries",
		getReadEntries: "history:get-read-entries",
	},
};

const events = {};

export { channels, events };
